---
- hosts: all
  tasks:
    - name: debug for
      shell: "{{item}}"
      with_items:
        - hostname
        - uname
      register: ret
    - name: xianshi bianlang
      debug: msg="{% for i in ret.results %} {{ i.stdout }} {% endfor %}"
